# Generated by Django 5.1.4 on 2025-01-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsuser',
            name='region',
            field=models.CharField(default='IRI', max_length=256),
        ),
    ]
